### PR TITLE
Import support for the updated Zoul-based platforms

### PR DESCRIPTION
**Pull request by alignan**
This PR includes support for the `zoul` module (a CC2538 + CC1200 beast), and based platforms, namely:

* RE-Mote revision A.
* Firefly
* Upcoming Ethernet gateway with the ENC28J60 and POE support (Q3 2016)

### CODE REVIEW

**Comment by laurentderu** [comment]
thanks for the contribution :)

**Comment by alignan** [comment]
:smile_cat:

**Comment by alignan** [comment]
A support page for the `Zolertia Ethernet IoT` Gateway and how to assemble one using the `Firefly` and `RE-Mote`:

https://github.com/Zolertia/Resources/wiki/6lbr

**Comment by laurentderu** [comment]
Thanks :) , and with the last bugs solved I will make a new official release soon.

**Pull request merged**
